// QUE ES UNA API?--->CONJUNTO DE FUNCIONES Y PROCEDIMIENTOS QUE CUMPLEN UNA O MUCHAS FUNCIONES CON EL FIN DE SER UTILIZADAS POR OTRO SOFTWARE
//                --->ES EL INTERMEDIARIO QUE LEE TU REQUEST Y NOS RESPONDE---->PUEDE HABER COMUNICACION ENTRE API'S--->CADA UNA PARA DIFERENTE PROPOSITO
// UNA API TIENE DIFERENTES ARQUITECTURAS----> REST Y RESTFUL
// REST---> ES LA ARQUITUCTURA QUE ME AYUDA A ENTENDER MEJOR UNA API
// RESFUL---> CUANDO SE QUIERE USAR EL ADJETIVO DE QUE ALGO ES REST   // TAMBIEN SE DENOMINA COMO UN SERVICIO QUE IMPLEMENTA REST
// ¿PARA QUE USAR REST? --->ES UNA ARQUITECTURA QUE SIRVE PARA TENER UN MEJOR CONTROL, CODIGO LIMPIO, MEJOR COMPRENSION DE LA API Y MEJOR ORGANIZACION

//¿CUALES SON SUS CARACTERISTICAS?--->
//1.- SE REQUIERE UN PROTOCOLO CLIENTE/SERVIDOR SIN ESTADO (HTTP)---->EL DECIR QUE NO TIENE ESTADO SIGNIFICA // LA API NO SABRA REALMENTE QUIENES SOMOS  // CADA VEZ QUE SE HAGA UN request SE VA A ENVIAR UN TOKEN DE ACCESO
//2.- CONJUNTO DE OPERACIONES DEFINIDAS (GET, POST, DELETE)
//3.- SINTAXIS UNIVERSAL (/recurso/identificador)
//4.- USO DE HIPERMEDIOS (HTML, XML, JSON)

